# Generated by Django 6.0.1 on 2026-01-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('limit', models.FloatField()),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('currency', models.CharField(choices=[('INR', '₹ Indian Rupee'), ('USD', '$ US Dollar'), ('EUR', '€ Euro'), ('GBP', '£ British Pound')], default='INR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_amount', models.FloatField()),
                ('current_amount', models.FloatField(default=0)),
                ('deadline', models.DateField()),
                ('currency', models.CharField(choices=[('INR', '₹ Indian Rupee'), ('USD', '$ US Dollar'), ('EUR', '€ Euro'), ('GBP', '£ British Pound')], default='INR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('INR', '₹ Indian Rupee'), ('USD', '$ US Dollar'), ('EUR', '€ Euro'), ('GBP', '£ British Pound')], default='INR', max_length=3)),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('INR', '₹ Indian Rupee'), ('USD', '$ US Dollar'), ('EUR', '€ Euro'), ('GBP', '£ British Pound')], default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurring_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, null=True),
        ),
    ]
